# Generated by Django 5.1.4 on 2025-01-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image_height_userprofile_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
    ]
