# Generated by Django 5.1.2 on 2024-12-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at'], 'verbose_name': 'Social Media Post', 'verbose_name_plural': 'Social Media Posts'},
        ),
    ]
