# Generated by Django 5.1.4 on 2025-01-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_comment_options_comment_likes_alter_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
    ]
